name: Connector Account Provisioning Test
description: Test account provisioning and deprovisioning for a baton connector that supports these capabilities.

inputs:
  connector:
    description: 'Connector binary to test'
    required: true
  account-email:
    description: 'Account email to test provisioning'
    required: true
  account-login:
    description: 'Account login to test provisioning'
    required: false
  account-display-name:
    description: 'Account display name to test provisioning'
    required: false
  account-profile:
    description: 'Account profile JSON to test provisioning'
    required: false
  account-type:
    description: 'Type of account to test provisioning. If not provided, will default to "user".'
    required: false
    default: 'user'
  search-method:
    description: 'Method to search for the created user: "email", "login", or "display_name". Defaults to "email".'
    required: false
    default: 'email'

runs:
  using: "composite"
  steps:
    - name: Download Baton
      uses: ConductorOne/github-workflows/actions/get-baton@v2

    - name: Account Provisioning Test
      env:
        BATON_CONNECTOR: ${{ inputs.connector }}
        ACCOUNT_LOGIN: ${{ inputs.account-login }}
        ACCOUNT_EMAIL: ${{ inputs.account-email }}
        ACCOUNT_DISPLAY_NAME: ${{ inputs.account-display-name }}
        ACCOUNT_PROFILE: ${{ inputs.account-profile }}
        ACCOUNT_TYPE: ${{ inputs.account-type }}
        SEARCH_METHOD: ${{ inputs.search-method }}
      run: ${{ github.action_path }}/account-provisioning.sh
      shell: bash
