## DEPRECATED: starting in v3, use files in templates/ instead.
## NOTE: v1 and v2 of release.yaml workflow reference this file directly from main,
## so you cannot change this file in any ways that breaks those workflow versions.
version: 2
project_name: "${REPO_NAME}"
builds:
  - binary: "${REPO_NAME}"
    env:
      - CGO_ENABLED=0
    id: linux
    main: ./cmd/${REPO_NAME}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    tags:
      - "baton_lambda_support"
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/conductorone/${REPO_NAME}:{{ .Version }}-amd64"
      - "ghcr.io/conductorone/${REPO_NAME}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/conductorone/${REPO_NAME}:{{ .Version }}-arm64"
      - "ghcr.io/conductorone/${REPO_NAME}:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: ghcr.io/conductorone/${REPO_NAME}:{{ .Version }}
    image_templates:
      - ghcr.io/conductorone/${REPO_NAME}:{{ .Version }}-amd64
      - ghcr.io/conductorone/${REPO_NAME}:{{ .Version }}-arm64
  - name_template: ghcr.io/conductorone/${REPO_NAME}:latest
    image_templates:
      - ghcr.io/conductorone/${REPO_NAME}:latest-amd64
      - ghcr.io/conductorone/${REPO_NAME}:latest-arm64
checksum:
  disable: true
release:
  disable: true
changelog:
  disable: true
