## NOTE: replaces .goreleaser-docker-template.yaml and .goreleaser-docker-template-no-lambda.yaml
## Consolidated docker template for GoReleaser >= 2.12 with optional lambda build
version: 2
project_name: "${REPO_NAME}"
builds:
  - binary: "${REPO_NAME}"
    env:
      - CGO_ENABLED=0
    id: linux
    main: ./cmd/${REPO_NAME}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    tags:
      - "baton_lambda_support"
dockers_v2:
  - id: ghcr
    images:
      - "ghcr.io/conductorone/${REPO_NAME}"
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: ${DOCKERFILE_PATH}
    ids:
      - linux
    disable: '{{ ne .Env.DOCKER "true" }}'
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
      "org.opencontainers.image.description": "ConductorOne Baton connector"
# note: ECR supports multi-arch images and OCI manifests, but annoyingly Lambda does not,
# so use the older dockers config to build a single-platform image with Docker v2 manifest
dockers:
  - id: ecr-lambda
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: ${DOCKERFILE_LAMBDA_PATH}
    image_templates:
      - "168442440833.dkr.ecr.us-west-2.amazonaws.com/${REPO_NAME}:{{ .Version }}-arm64"
    skip_push: '{{ ne .Env.LAMBDA "true" }}'
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
docker_digest:
  name_template: "{{ .ProjectName }}_{{ .Version }}_digests.txt"
# sign each image by digest
docker_signs:
  - id: cosign-images
    output: true
    cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - "sign"
      - "--yes"
      - "{{ .Env.artifact }}@{{ .Env.digest }}"
checksum:
  disable: true
release:
  disable: true
changelog:
  disable: true
