// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: artifacts/v1/manifest.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Manifest represents the immutable artifact metadata for a specific release version.
// This manifest is stored at the versioned path: releases/{org}/{repo}/{tag}/manifest.json
type Manifest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Version         *string                `protobuf:"bytes,1,opt,name=version"`
	xxx_hidden_Name            *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Org             *string                `protobuf:"bytes,3,opt,name=org"`
	xxx_hidden_Semver          *string                `protobuf:"bytes,4,opt,name=semver"`
	xxx_hidden_ReleasedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=released_at,json=releasedAt"`
	xxx_hidden_Assets          map[string]*Asset      `protobuf:"bytes,6,rep,name=assets" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Images          map[string]*Image      `protobuf:"bytes,7,rep,name=images" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_SignatureHref   *string                `protobuf:"bytes,8,opt,name=signature_href,json=signatureHref"`
	xxx_hidden_CertificateHref *string                `protobuf:"bytes,9,opt,name=certificate_href,json=certificateHref"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_artifacts_v1_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_v1_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *Manifest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Manifest) GetOrg() string {
	if x != nil {
		if x.xxx_hidden_Org != nil {
			return *x.xxx_hidden_Org
		}
		return ""
	}
	return ""
}

func (x *Manifest) GetSemver() string {
	if x != nil {
		if x.xxx_hidden_Semver != nil {
			return *x.xxx_hidden_Semver
		}
		return ""
	}
	return ""
}

func (x *Manifest) GetReleasedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ReleasedAt
	}
	return nil
}

func (x *Manifest) GetAssets() map[string]*Asset {
	if x != nil {
		return x.xxx_hidden_Assets
	}
	return nil
}

func (x *Manifest) GetImages() map[string]*Image {
	if x != nil {
		return x.xxx_hidden_Images
	}
	return nil
}

func (x *Manifest) GetSignatureHref() string {
	if x != nil {
		if x.xxx_hidden_SignatureHref != nil {
			return *x.xxx_hidden_SignatureHref
		}
		return ""
	}
	return ""
}

func (x *Manifest) GetCertificateHref() string {
	if x != nil {
		if x.xxx_hidden_CertificateHref != nil {
			return *x.xxx_hidden_CertificateHref
		}
		return ""
	}
	return ""
}

func (x *Manifest) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *Manifest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *Manifest) SetOrg(v string) {
	x.xxx_hidden_Org = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *Manifest) SetSemver(v string) {
	x.xxx_hidden_Semver = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *Manifest) SetReleasedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ReleasedAt = v
}

func (x *Manifest) SetAssets(v map[string]*Asset) {
	x.xxx_hidden_Assets = v
}

func (x *Manifest) SetImages(v map[string]*Image) {
	x.xxx_hidden_Images = v
}

func (x *Manifest) SetSignatureHref(v string) {
	x.xxx_hidden_SignatureHref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *Manifest) SetCertificateHref(v string) {
	x.xxx_hidden_CertificateHref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *Manifest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Manifest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Manifest) HasOrg() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Manifest) HasSemver() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Manifest) HasReleasedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ReleasedAt != nil
}

func (x *Manifest) HasSignatureHref() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Manifest) HasCertificateHref() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *Manifest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Version = nil
}

func (x *Manifest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Manifest) ClearOrg() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Org = nil
}

func (x *Manifest) ClearSemver() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Semver = nil
}

func (x *Manifest) ClearReleasedAt() {
	x.xxx_hidden_ReleasedAt = nil
}

func (x *Manifest) ClearSignatureHref() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_SignatureHref = nil
}

func (x *Manifest) ClearCertificateHref() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_CertificateHref = nil
}

type Manifest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// version is the manifest schema version (currently "1")
	Version *string
	// name is the repository name (e.g., "baton-ukg")
	Name *string
	// org is the organization name (e.g., "ConductorOne")
	Org *string
	// semver is the semantic version tag (e.g., "v0.0.8")
	Semver *string
	// released_at is the timestamp when the release was created
	ReleasedAt *timestamppb.Timestamp
	// assets is a map of platform/type identifiers to asset metadata.
	// Keys are platform identifiers like "darwin-arm64", "linux-amd64", "windows-amd64", "checksums"
	Assets map[string]*Asset
	// images is a map of registry identifiers to container image metadata.
	// Keys are registry identifiers like "ghcr", "ecr-public"
	Images map[string]*Image
	// signature_href is the URL to the manifest signature file (manifest.json.sig)
	SignatureHref *string
	// certificate_href is the URL to the manifest certificate file (manifest.json.cert)
	CertificateHref *string
}

func (b0 Manifest_builder) Build() *Manifest {
	m0 := &Manifest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_Version = b.Version
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Name = b.Name
	}
	if b.Org != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Org = b.Org
	}
	if b.Semver != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Semver = b.Semver
	}
	x.xxx_hidden_ReleasedAt = b.ReleasedAt
	x.xxx_hidden_Assets = b.Assets
	x.xxx_hidden_Images = b.Images
	if b.SignatureHref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_SignatureHref = b.SignatureHref
	}
	if b.CertificateHref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_CertificateHref = b.CertificateHref
	}
	return m0
}

// Asset represents metadata for a single binary artifact.
type Asset struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filename        *string                `protobuf:"bytes,1,opt,name=filename"`
	xxx_hidden_MediaType       *string                `protobuf:"bytes,2,opt,name=media_type,json=mediaType"`
	xxx_hidden_SizeBytes       int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes"`
	xxx_hidden_Sha256          *string                `protobuf:"bytes,4,opt,name=sha256"`
	xxx_hidden_Href            *string                `protobuf:"bytes,5,opt,name=href"`
	xxx_hidden_SignatureHref   *string                `protobuf:"bytes,6,opt,name=signature_href,json=signatureHref"`
	xxx_hidden_CertificateHref *string                `protobuf:"bytes,7,opt,name=certificate_href,json=certificateHref"`
	xxx_hidden_SbomHref        *string                `protobuf:"bytes,8,opt,name=sbom_href,json=sbomHref"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_artifacts_v1_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_v1_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Asset) GetFilename() string {
	if x != nil {
		if x.xxx_hidden_Filename != nil {
			return *x.xxx_hidden_Filename
		}
		return ""
	}
	return ""
}

func (x *Asset) GetMediaType() string {
	if x != nil {
		if x.xxx_hidden_MediaType != nil {
			return *x.xxx_hidden_MediaType
		}
		return ""
	}
	return ""
}

func (x *Asset) GetSizeBytes() int64 {
	if x != nil {
		return x.xxx_hidden_SizeBytes
	}
	return 0
}

func (x *Asset) GetSha256() string {
	if x != nil {
		if x.xxx_hidden_Sha256 != nil {
			return *x.xxx_hidden_Sha256
		}
		return ""
	}
	return ""
}

func (x *Asset) GetHref() string {
	if x != nil {
		if x.xxx_hidden_Href != nil {
			return *x.xxx_hidden_Href
		}
		return ""
	}
	return ""
}

func (x *Asset) GetSignatureHref() string {
	if x != nil {
		if x.xxx_hidden_SignatureHref != nil {
			return *x.xxx_hidden_SignatureHref
		}
		return ""
	}
	return ""
}

func (x *Asset) GetCertificateHref() string {
	if x != nil {
		if x.xxx_hidden_CertificateHref != nil {
			return *x.xxx_hidden_CertificateHref
		}
		return ""
	}
	return ""
}

func (x *Asset) GetSbomHref() string {
	if x != nil {
		if x.xxx_hidden_SbomHref != nil {
			return *x.xxx_hidden_SbomHref
		}
		return ""
	}
	return ""
}

func (x *Asset) SetFilename(v string) {
	x.xxx_hidden_Filename = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *Asset) SetMediaType(v string) {
	x.xxx_hidden_MediaType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *Asset) SetSizeBytes(v int64) {
	x.xxx_hidden_SizeBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *Asset) SetSha256(v string) {
	x.xxx_hidden_Sha256 = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *Asset) SetHref(v string) {
	x.xxx_hidden_Href = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *Asset) SetSignatureHref(v string) {
	x.xxx_hidden_SignatureHref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *Asset) SetCertificateHref(v string) {
	x.xxx_hidden_CertificateHref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *Asset) SetSbomHref(v string) {
	x.xxx_hidden_SbomHref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *Asset) HasFilename() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Asset) HasMediaType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Asset) HasSizeBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Asset) HasSha256() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Asset) HasHref() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Asset) HasSignatureHref() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Asset) HasCertificateHref() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Asset) HasSbomHref() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Asset) ClearFilename() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Filename = nil
}

func (x *Asset) ClearMediaType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MediaType = nil
}

func (x *Asset) ClearSizeBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SizeBytes = 0
}

func (x *Asset) ClearSha256() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Sha256 = nil
}

func (x *Asset) ClearHref() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Href = nil
}

func (x *Asset) ClearSignatureHref() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_SignatureHref = nil
}

func (x *Asset) ClearCertificateHref() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_CertificateHref = nil
}

func (x *Asset) ClearSbomHref() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_SbomHref = nil
}

type Asset_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// filename is the name of the artifact file (e.g., "baton-ukg-v0.0.8-darwin-arm64.zip")
	Filename *string
	// media_type is the MIME type of the artifact (e.g., "application/zip", "application/gzip", "text/plain")
	MediaType *string
	// size_bytes is the size of the artifact in bytes
	SizeBytes *int64
	// sha256 is the SHA-256 checksum of the artifact in hexadecimal format
	Sha256 *string
	// href is the URL to download the artifact
	Href *string
	// signature_href is the URL to the artifact signature file (filename.sig)
	SignatureHref *string
	// certificate_href is the URL to the artifact certificate file (filename.cert)
	CertificateHref *string
	// sbom_href is the optional URL to the Software Bill of Materials file (filename.sbom.json)
	SbomHref *string
}

func (b0 Asset_builder) Build() *Asset {
	m0 := &Asset{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Filename != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Filename = b.Filename
	}
	if b.MediaType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_MediaType = b.MediaType
	}
	if b.SizeBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_SizeBytes = *b.SizeBytes
	}
	if b.Sha256 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Sha256 = b.Sha256
	}
	if b.Href != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Href = b.Href
	}
	if b.SignatureHref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_SignatureHref = b.SignatureHref
	}
	if b.CertificateHref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_CertificateHref = b.CertificateHref
	}
	if b.SbomHref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_SbomHref = b.SbomHref
	}
	return m0
}

// Image represents metadata for a container image.
type Image struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *string                `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Digest      *string                `protobuf:"bytes,2,opt,name=digest"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_artifacts_v1_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_v1_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Image) GetRef() string {
	if x != nil {
		if x.xxx_hidden_Ref != nil {
			return *x.xxx_hidden_Ref
		}
		return ""
	}
	return ""
}

func (x *Image) GetDigest() string {
	if x != nil {
		if x.xxx_hidden_Digest != nil {
			return *x.xxx_hidden_Digest
		}
		return ""
	}
	return ""
}

func (x *Image) SetRef(v string) {
	x.xxx_hidden_Ref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Image) SetDigest(v string) {
	x.xxx_hidden_Digest = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Image) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Image) HasDigest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Image) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Ref = nil
}

func (x *Image) ClearDigest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Digest = nil
}

type Image_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// ref is the full image reference (e.g., "ghcr.io/conductorone/baton-ukg:v0.0.8")
	Ref *string
	// digest is the image digest in the format "sha256:<hex>" (e.g., "sha256:abc123...")
	Digest *string
}

func (b0 Image_builder) Build() *Image {
	m0 := &Image{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Ref = b.Ref
	}
	if b.Digest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Digest = b.Digest
	}
	return m0
}

var File_artifacts_v1_manifest_proto protoreflect.FileDescriptor

const file_artifacts_v1_manifest_proto_rawDesc = "" +
	"\n" +
	"\x1bartifacts/v1/manifest.proto\x12\fartifacts.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!google/protobuf/go_features.proto\"\x89\x04\n" +
	"\bManifest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x12\x16\n" +
	"\x06semver\x18\x04 \x01(\tR\x06semver\x12;\n" +
	"\vreleased_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"releasedAt\x12:\n" +
	"\x06assets\x18\x06 \x03(\v2\".artifacts.v1.Manifest.AssetsEntryR\x06assets\x12:\n" +
	"\x06images\x18\a \x03(\v2\".artifacts.v1.Manifest.ImagesEntryR\x06images\x12%\n" +
	"\x0esignature_href\x18\b \x01(\tR\rsignatureHref\x12)\n" +
	"\x10certificate_href\x18\t \x01(\tR\x0fcertificateHref\x1aN\n" +
	"\vAssetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.artifacts.v1.AssetR\x05value:\x028\x01\x1aN\n" +
	"\vImagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.artifacts.v1.ImageR\x05value:\x028\x01\"\xfc\x01\n" +
	"\x05Asset\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04href\x18\x05 \x01(\tR\x04href\x12%\n" +
	"\x0esignature_href\x18\x06 \x01(\tR\rsignatureHref\x12)\n" +
	"\x10certificate_href\x18\a \x01(\tR\x0fcertificateHref\x12\x1b\n" +
	"\tsbom_href\x18\b \x01(\tR\bsbomHref\"1\n" +
	"\x05Image\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digestBBZ8github.com/ConductorOne/github-workflows/pb/artifacts/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_artifacts_v1_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_artifacts_v1_manifest_proto_goTypes = []any{
	(*Manifest)(nil),              // 0: artifacts.v1.Manifest
	(*Asset)(nil),                 // 1: artifacts.v1.Asset
	(*Image)(nil),                 // 2: artifacts.v1.Image
	nil,                           // 3: artifacts.v1.Manifest.AssetsEntry
	nil,                           // 4: artifacts.v1.Manifest.ImagesEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_artifacts_v1_manifest_proto_depIdxs = []int32{
	5, // 0: artifacts.v1.Manifest.released_at:type_name -> google.protobuf.Timestamp
	3, // 1: artifacts.v1.Manifest.assets:type_name -> artifacts.v1.Manifest.AssetsEntry
	4, // 2: artifacts.v1.Manifest.images:type_name -> artifacts.v1.Manifest.ImagesEntry
	1, // 3: artifacts.v1.Manifest.AssetsEntry.value:type_name -> artifacts.v1.Asset
	2, // 4: artifacts.v1.Manifest.ImagesEntry.value:type_name -> artifacts.v1.Image
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_artifacts_v1_manifest_proto_init() }
func file_artifacts_v1_manifest_proto_init() {
	if File_artifacts_v1_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifacts_v1_manifest_proto_rawDesc), len(file_artifacts_v1_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_artifacts_v1_manifest_proto_goTypes,
		DependencyIndexes: file_artifacts_v1_manifest_proto_depIdxs,
		MessageInfos:      file_artifacts_v1_manifest_proto_msgTypes,
	}.Build()
	File_artifacts_v1_manifest_proto = out.File
	file_artifacts_v1_manifest_proto_goTypes = nil
	file_artifacts_v1_manifest_proto_depIdxs = nil
}
