// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: artifacts/v1/stable.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stable represents a pointer to the current stable release with metadata.
// This manifest is stored at the catalog-level path: releases/{org}/{repo}/stable.json
type Stable struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Version     *string                `protobuf:"bytes,1,opt,name=version"`
	xxx_hidden_UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_Manifest    *Manifest              `protobuf:"bytes,3,opt,name=manifest"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Stable) Reset() {
	*x = Stable{}
	mi := &file_artifacts_v1_stable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stable) ProtoMessage() {}

func (x *Stable) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_v1_stable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Stable) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *Stable) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Stable) GetManifest() *Manifest {
	if x != nil {
		return x.xxx_hidden_Manifest
	}
	return nil
}

func (x *Stable) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Stable) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Stable) SetManifest(v *Manifest) {
	x.xxx_hidden_Manifest = v
}

func (x *Stable) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Stable) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Stable) HasManifest() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Manifest != nil
}

func (x *Stable) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Version = nil
}

func (x *Stable) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

func (x *Stable) ClearManifest() {
	x.xxx_hidden_Manifest = nil
}

type Stable_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// version is the stable schema version (currently "1")
	Version *string
	// updated_at is the timestamp when stable.json was last updated.
	// This differs from manifest.released_at which is when the release was originally created.
	UpdatedAt *timestamppb.Timestamp
	// manifest is the manifest for the current stable release
	Manifest *Manifest
}

func (b0 Stable_builder) Build() *Stable {
	m0 := &Stable{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Version = b.Version
	}
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_Manifest = b.Manifest
	return m0
}

var File_artifacts_v1_stable_proto protoreflect.FileDescriptor

const file_artifacts_v1_stable_proto_rawDesc = "" +
	"\n" +
	"\x19artifacts/v1/stable.proto\x12\fartifacts.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!google/protobuf/go_features.proto\x1a\x1bartifacts/v1/manifest.proto\"\x91\x01\n" +
	"\x06Stable\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x122\n" +
	"\bmanifest\x18\x03 \x01(\v2\x16.artifacts.v1.ManifestR\bmanifestBBZ8github.com/ConductorOne/github-workflows/pb/artifacts/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_artifacts_v1_stable_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_artifacts_v1_stable_proto_goTypes = []any{
	(*Stable)(nil),                // 0: artifacts.v1.Stable
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*Manifest)(nil),              // 2: artifacts.v1.Manifest
}
var file_artifacts_v1_stable_proto_depIdxs = []int32{
	1, // 0: artifacts.v1.Stable.updated_at:type_name -> google.protobuf.Timestamp
	2, // 1: artifacts.v1.Stable.manifest:type_name -> artifacts.v1.Manifest
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_artifacts_v1_stable_proto_init() }
func file_artifacts_v1_stable_proto_init() {
	if File_artifacts_v1_stable_proto != nil {
		return
	}
	file_artifacts_v1_manifest_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifacts_v1_stable_proto_rawDesc), len(file_artifacts_v1_stable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_artifacts_v1_stable_proto_goTypes,
		DependencyIndexes: file_artifacts_v1_stable_proto_depIdxs,
		MessageInfos:      file_artifacts_v1_stable_proto_msgTypes,
	}.Build()
	File_artifacts_v1_stable_proto = out.File
	file_artifacts_v1_stable_proto_goTypes = nil
	file_artifacts_v1_stable_proto_depIdxs = nil
}
