// Command generate-brew-formula renders a Homebrew formula from a merged release manifest.
//
// GoReleaser used to render this formula as part of the binaries run, but that run now only
// builds the darwin targets (linux moved to its own job so it can compile in parallel), so
// GoReleaser can no longer see the linux archives the tap's on_linux blocks need. This tool
// renders the formula from the merged manifest instead, where every platform is present.
//
// Download URLs point at the CDN rather than GitHub release assets: the CDN is the canonical
// distribution channel and is what the connector registry records.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strings"
	"text/template"

	"google.golang.org/protobuf/encoding/protojson"

	pb "github.com/ConductorOne/github-workflows/pb/artifacts/v1"
)

// platformBlock is one `url`/`sha256` pair rendered inside an on_macos/on_linux block.
type platformBlock struct {
	Condition string
	URL       string
	SHA256    string
}

type formulaData struct {
	Class    string
	Binary   string
	Homepage string
	Version  string
	MacOS    []platformBlock
	Linux    []platformBlock
}

// formulaTemplate mirrors the layout GoReleaser produced so the tap diff stays reviewable.
const formulaTemplate = `# typed: false
# frozen_string_literal: true

# This file was generated by ConductorOne/github-workflows. DO NOT EDIT.
class {{ .Class }} < Formula
  desc ""
  homepage "{{ .Homepage }}"
  version "{{ .Version }}"
{{ if .MacOS }}
  on_macos do
{{- range .MacOS }}
    if {{ .Condition }}
      url "{{ .URL }}"
      sha256 "{{ .SHA256 }}"

      def install
        bin.install "{{ $.Binary }}"
      end
    end
{{- end }}
  end
{{- end }}
{{ if .Linux }}
  on_linux do
{{- range .Linux }}
    if {{ .Condition }}
      url "{{ .URL }}"
      sha256 "{{ .SHA256 }}"

      def install
        bin.install "{{ $.Binary }}"
      end
    end
{{- end }}
  end
{{- end }}

  test do
    system "#{bin}/{{ .Binary }} -v"
  end
end
`

func main() {
	var (
		manifestPath string
		outputPath   string
		homepage     string
	)
	flag.StringVar(&manifestPath, "manifest", "", "Path to the merged manifest.json")
	flag.StringVar(&outputPath, "output", "", "Path to write the rendered formula")
	flag.StringVar(&homepage, "homepage", "https://conductorone.com", "Formula homepage")
	flag.Parse()

	if manifestPath == "" || outputPath == "" {
		fmt.Fprintf(os.Stderr, "generate-brew-formula: error: manifest and output are required\n")
		os.Exit(1)
	}

	raw, err := os.ReadFile(manifestPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate-brew-formula: error: reading manifest: %v\n", err)
		os.Exit(1)
	}

	manifest := &pb.Manifest{}
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(raw, manifest); err != nil {
		fmt.Fprintf(os.Stderr, "generate-brew-formula: error: parsing manifest: %v\n", err)
		os.Exit(1)
	}

	name := manifest.GetName()
	if name == "" {
		fmt.Fprintf(os.Stderr, "generate-brew-formula: ::error::Manifest is missing 'name'\n")
		os.Exit(1)
	}

	data := formulaData{
		Class:    formulaClass(name),
		Binary:   name,
		Homepage: homepage,
		Version:  strings.TrimPrefix(manifest.GetSemver(), "v"),
	}

	// Ordering matches GoReleaser's output: intel before arm within each OS block.
	macOSPlatforms := []struct{ key, condition string }{
		{"darwin-amd64", "Hardware::CPU.intel?"},
		{"darwin-arm64", "Hardware::CPU.arm?"},
	}
	linuxPlatforms := []struct{ key, condition string }{
		{"linux-amd64", "Hardware::CPU.intel? && Hardware::CPU.is_64_bit?"},
		{"linux-arm64", "Hardware::CPU.arm? && Hardware::CPU.is_64_bit?"},
	}

	assets := manifest.GetAssets()
	for _, p := range macOSPlatforms {
		if block, ok := blockFor(assets, p.key, p.condition); ok {
			data.MacOS = append(data.MacOS, block)
		}
	}
	for _, p := range linuxPlatforms {
		if block, ok := blockFor(assets, p.key, p.condition); ok {
			data.Linux = append(data.Linux, block)
		}
	}

	// A formula with no platforms would silently uninstall the connector for every user.
	if len(data.MacOS) == 0 && len(data.Linux) == 0 {
		fmt.Fprintf(os.Stderr, "generate-brew-formula: ::error::Manifest contains no darwin or linux assets\n")
		os.Exit(1)
	}

	rendered, err := renderFormula(data)
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate-brew-formula: error: rendering formula: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputPath, rendered, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "generate-brew-formula: error: writing formula: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "✅ Generated formula for %s (%d macOS, %d linux platforms)\n",
		name, len(data.MacOS), len(data.Linux))
}

// renderFormula renders the Homebrew formula for data.
func renderFormula(data formulaData) ([]byte, error) {
	tmpl, err := template.New("formula").Parse(formulaTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}
	return buf.Bytes(), nil
}

// blockFor builds the template block for one platform, reporting false when the manifest
// has no asset for it (for example a connector that does not ship a darwin build).
func blockFor(assets map[string]*pb.Asset, key, condition string) (platformBlock, bool) {
	asset, ok := assets[key]
	if !ok || asset.GetHref() == "" || asset.GetSha256() == "" {
		return platformBlock{}, false
	}
	return platformBlock{
		Condition: condition,
		URL:       asset.GetHref(),
		SHA256:    asset.GetSha256(),
	}, true
}

// formulaClass converts a repository name into the Ruby class name Homebrew expects,
// matching GoReleaser's behaviour: "baton-okta" becomes "BatonOkta".
func formulaClass(name string) string {
	var b strings.Builder
	for _, part := range strings.FieldsFunc(name, func(r rune) bool {
		return r == '-' || r == '_' || r == '.' || r == ' '
	}) {
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}
