## Docker template for signed OCI images, pushes to GHCR
## GoReleaser >= 2.12 required for dockers_v2
version: 2
project_name: "${REPO_NAME}"
builds:
  - binary: "${REPO_NAME}"
    env:
      - CGO_ENABLED=0
    id: linux
    main: ./cmd/${REPO_NAME}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers_v2:
  - id: ghcr
    images:
      - "ghcr.io/conductorone/${REPO_NAME}"
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: ${DOCKERFILE_PATH}
    ids:
      - linux
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
      "org.opencontainers.image.description": "ConductorOne Baton connector"
docker_digest:
  name_template: "{{ .ProjectName }}_{{ .Version }}_digests.txt"
# sign each image by digest
docker_signs:
  - id: cosign-images
    output: true
    cmd: cosign
    artifacts: image
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - "sign"
      - "--yes"
      - "{{ .Env.artifact }}@{{ .Env.digest }}"
checksum:
  disable: true
release:
  disable: true
changelog:
  disable: true
