## Binary template for signed artifacts, pushes to public registry (S3 bucket)
version: 2
project_name: "${REPO_NAME}"
builds:
  - binary: "${REPO_NAME}"
    env:
      - CGO_ENABLED=0
    id: linux
    main: ./cmd/${REPO_NAME}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - binary: "${REPO_NAME}"
    env:
      - CGO_ENABLED=0
    id: windows
    main: ./cmd/${REPO_NAME}
    goos:
      - windows
    goarch:
      - amd64
  - binary: "${REPO_NAME}"
    env:
      - CGO_ENABLED=0
    id: macos-amd64
    main: ./cmd/${REPO_NAME}
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post:
        - gon ../_workflows/_generated/.gon-amd64.json
  - binary: "${REPO_NAME}"
    env:
      - CGO_ENABLED=0
    id: macos-arm64
    main: ./cmd/${REPO_NAME}
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post:
        - gon ../_workflows/_generated/.gon-arm64.json
archives:
  - id: linux-archive
    builds:
      - linux
    format: tar.gz
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - none*
  - id: windows-archive
    builds:
      - windows
    format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - none*
  - id: darwin-archive
    builds:
      - macos-amd64
      - macos-arm64
    format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - none*
release:
  ids:
    - linux-archive
    - windows-archive
    - darwin-archive
snapshot:
  version_template: "{{ incpatch .Version }}-dev"
checksum:
  ids:
    - linux-archive
    - windows-archive
    - darwin-archive
sboms:
  - artifacts: archive
signs:
  - id: cosign-archives
    output: true
    cmd: cosign
    artifacts: archive
    ids:
      - linux-archive
      - windows-archive
      - darwin-archive
    certificate: "{{ .Env.artifact }}.cert"
    args:
      - "sign-blob"
      - "--yes"
      - "--output-signature={{ .Env.signature }}"
      - "--output-certificate={{ .Env.certificate }}"
      - "{{ .Env.artifact }}"
    env:
      - COSIGN_EXPERIMENTAL=1
  - id: cosign-checksums
    output: true
    cmd: cosign
    artifacts: checksum
    certificate: "{{ .Env.artifact }}.cert"
    args:
      - "sign-blob"
      - "--yes"
      - "--output-signature={{ .Env.signature }}"
      - "--output-certificate={{ .Env.certificate }}"
      - "{{ .Env.artifact }}"
    env:
      - COSIGN_EXPERIMENTAL=1
brews:
  - repository:
      owner: conductorone
      name: homebrew-baton
    directory: Formula
    homepage: https://conductorone.com
    test: |
      system "#{bin}/${REPO_NAME} -v"
    install: |-
      bin.install "${REPO_NAME}"
changelog:
  filters:
    exclude:
      - "^docs:"
      - typo
      - lint
      - Merge pull request
blobs:
  - provider: s3
    bucket: "${S3_BUCKET}"
    region: "${S3_REGION}"
    directory: "${S3_DIRECTORY}"
    ids:
      - linux-archive
      - windows-archive
      - darwin-archive
      - checksum
    extra_files:
      - glob: dist/*.sig
      - glob: dist/*.cert
      - glob: dist/*.sbom.json
    cache_control:
      - "public,max-age=31536000,immutable"
    content_disposition: "-"
