on:
  workflow_call:

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout caller repo
      uses: actions/checkout@v5
      with:
        path: _caller
        repository: ${{ github.event.repository.full_name }}
        fetch-depth: 0
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: _caller/go.mod
    - name: Run linters
      uses: golangci/golangci-lint-action@v8
      with:
       version: latest
       args: --timeout=3m
       working-directory: _caller